---
- name: "System / Tools / Deploy / Package / Provision OS tool ({{
    sys_tools___deploy_tool }})"
  vars:
    sys_package:
      provision: true
    sys_package_application: "{{ sys_tools_application[sys_tools___deploy_tool] }}"
    sys_package_profiles: "{{ sys_tools_profiles[sys_tools___deploy_tool] }}"
  ansible.builtin.include_role:
    name: "serdigital64.system.sys_package"
...
