---
- name: "Verify"
  hosts: oel
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_repository"

    - name: "Identify enabled repositories"
      ansible.builtin.command:
        argv:
          - "{{ sys_repository_base['run']['dnf'] }}"
          - "--enabled"
          - "repolist"
      register: result
      changed_when: false

    - name: "Verify repository is enabled"
      ansible.builtin.assert:
        that:
          - result['stdout_lines'] is search( 'ol8_addons' )
...
