---
# Define supported platforms
sys_dconf_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

# Group Linux Distributions by family
sys_dconf_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'Linux' }}
  {%- endif -%}
  "

sys_dconf_application:
  name: "dconf"
  type: "distro"
  version: "latest"
  installed: true

# Multiplatform packages
sys_dconf_profiles_common:
  snap: {}
  flatpak: {}

# Define common paths
sys_dconf_base_common:
  access:
    user:
      owner: "root"
    group:
      owner: "root"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates:
    profile_user: "profile_user.j2"
  run: {}
  etc: {}
  paths: {}
  files: {}

# Temporary loop variables
# sys_dconf___prepare_path
# sys_dconf___provision_db
...
