---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_package:
          provision: true
        sys_package_application:
          name: "azure-cli"
          type: "rpm"
          version: "latest"
          installed: true
        sys_package_profiles:
          rpm:
            latest:
              origin: "https://packages.microsoft.com/yumrepos/azure-cli"
              packages:
                - file: "azure-cli-2.21.0-1.el7.x86_64.rpm"
                  name: "azure-cli"
      ansible.builtin.include_role:
        name: "sys_package"
...
