---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_tools:
          deploy: true
        sys_tools_catalog:
          file: true
          groff: true
          less: true
          sed: true
          gawk: true
          grep: true
          lsof: true
      ansible.builtin.include_role:
        name: "sys_tools"
...
