---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_tools"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_tools_profiles['file'][
          sys_tools_application['file']['type']
        ][
          sys_tools_application['file']['version']
        ]['packages']
        }}"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_tools_profiles['groff'][
          sys_tools_application['groff']['type']
        ][
          sys_tools_application['groff']['version']
        ]['packages']
        }}"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_tools_profiles['less'][
          sys_tools_application['less']['type']
        ][
          sys_tools_application['less']['version']
        ]['packages']
        }}"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_tools_profiles['gawk'][
          sys_tools_application['gawk']['type']
        ][
          sys_tools_application['gawk']['version']
        ]['packages']
        }}"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_tools_profiles['grep'][
          sys_tools_application['grep']['type']
        ][
          sys_tools_application['grep']['version']
        ]['packages']
        }}"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_tools_profiles['sed'][
          sys_tools_application['sed']['type']
        ][
          sys_tools_application['sed']['version']
        ]['packages']
        }}"

    - name: "Verify required packages are deployed (package: {{ item }})"
      ansible.builtin.assert:
        that:
          - item['name'] in ansible_facts['packages']
      loop: "{{
        sys_tools_profiles['lsof'][
          sys_tools_application['lsof']['type']
        ][
          sys_tools_application['lsof']['version']
        ]['packages']
        }}"
...
