---
namespace: "serdigital64"
name: "system"
version: "1.8.2"
readme: "README.md"
authors:
  - "SerDigital64 <https://github.com/serdigital64>"
description: "Ansible Roles for automating operating system management"
license:
  - "GPL-3.0-or-later"
tags:
  - "linux"
  - "system"
  - "tools"
dependencies:
  ansible.posix: "*"
  community.general: "*"
  serdigital64.automation: "*"
  serdigital64.backup: "*"
  serdigital64.development: "*"
  serdigital64.devops: "*"
repository: "https://github.com/serdigital64/aplatform64"
homepage: "https://github.com/serdigital64/aplatform64"
issues: "https://github.com/serdigital64/aplatform64/issues"
documentation: "https://aplatform64.readthedocs.io"
...
