---
sys_repository_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

sys_repository_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}
  "

sys_repository_flavours:
  - "distro"
  - "yum"
  - "apt"
  - "snap"
  - "flatpak"
  - "git"
  - "pip"

sys_repository_base_templates:
  yum_repo: "yum_repo.ini.j2"
  apt_list: "deb_list.ini.j2"

sys_repository_base_access:
  group: "root"
  owner: "root"
  mode:
    dir: "0755"
    file: "0644"
    exe: "0755"

sys_repository_alert_ansible_managed_file:
  "Warning: This file is automatically generated by the Ansible Role: serdigital64.system.sys_repository. Do not modify."

sys_repository___setup_repo: ~
sys_repository___setup_result: ~
sys_repository___provision_sources: ~
sys_repository___provision_result: ~
sys_repository___provision_test: ~
sys_repository___deploy_result: ~
# sys_repository___setup_repo_enable
# sys_repository___setup_repo_disable
# sys_repository___provision_repo_distro
# sys_repository___provision_repo_flatpak
# sys_repository___provision_repo_yum
# sys_repository___provision_repo_apt
...
