---
sys_repository_base:
  access:
    user:
      owner: "root"
      homebrew: "{{ sys_repository_owners['homebrew']['user'] }}"  # =X= #
    group:
      owner: "root"
      homebrew: "{{ sys_repository_owners['homebrew']['group'] }}"  # =X= #
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"
  templates: "{{ sys_repository_base_common['templates'] }}"
  etc:
    yum_repos_d: "/etc/yum.repos.d"
  run:
    su: "/bin/su"   # =X= #
    systemctl: "/usr/bin/systemctl"
    curl: "/usr/bin/curl"
    flatpak: "/usr/bin/flatpak"
    snap: "/usr/bin/snap"
    dnf: "/usr/bin/dnf"
    rpm: "/usr/bin/rpm"
    git: "/usr/bin/git"
    python: "/usr/bin/python3.9"
    brew: "/home/linuxbrew/.linuxbrew/bin/brew"  # =X= #
    brew_installer: "/home/linuxbrew/install.sh"  # =X= #
  paths:
    homebrew: "/home/linuxbrew/.linuxbrew"  # =X= #
    homebrew_home: "/home/linuxbrew"  # =X= #
    snap_root: "/snap"
    snap_bin: "/snap/bin"
    snap_var: "/var/lib/snapd/snap"

sys_repository_packages:
  distro:
    - "dnf-plugins-core"
    - "ca-certificates"
  flatpak:
    - "flatpak"
  git:
    - "git"
  tools:
    - "curl"
  snap:
    - "snapd"
  pip:    # source: dev_python_profiles@dev_python
    - "python39"
    - "python39-pip"
    - "python39-setuptools"
    - "python39-wheel"
    - "which"

sys_repository_sources:
  distro:
    - name: "epel"
      package: "epel-release"
  flatpak:
    - name: "flathub"
      url: "https://flathub.org/repo/flathub.flatpakrepo"
  yum: []
  apt: []
  brew:  # =X= #
    - name: "installer"
      url: "https://raw.githubusercontent.com/Homebrew/install/master/install.sh"
...
