---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_repository"

    - name: "Identify enabled repositories"
      ansible.builtin.stat:
        path: "{{ sys_repository_base['etc']['sources_list_d'] + '/azure-cli.list' }}"
      register: file_stat

    - name: "Verify repository is installed"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
