---
sys_mc_platforms:
  - "CentOS8"
  - "RedHat8"
  - "AlmaLinux8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"
  - "MacOSX12"

sys_mc_os_family: "
  {%- if
      ( ansible_distribution == 'CentOS' ) or
      ( ansible_distribution == 'RedHat' ) or
      ( ansible_distribution == 'AlmaLinux' ) or
      ( ansible_distribution == 'OracleLinux' ) or
      ( ansible_distribution == 'Fedora' )
  -%}
    {{ 'RedHat' }}
  {%- elif
      ( ansible_distribution == 'Debian' ) or
      ( ansible_distribution == 'Ubuntu' )
  -%}
    {{ 'Ubuntu' }}
  {%- elif
      ( ansible_distribution == 'MacOSX' )
  -%}
    {{ 'MacOSX' }}
  {%- else -%}
    {{ 'NotSupported' }}
  {%- endif -%}
  "

sys_mc_base_common:
  etc:
    mc: ".config/mc"
    ini: ".config/mc/ini"
    panels: ".config/mc/panels.ini"
  access:
    mode:
      dir: "0700"
      file: "0600"
  templates:
    ini: "ini.j2"
    panels: "panels.ini.j2"

# loop vars
# sys_mc___setup_user
...
