---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision"
      vars:
        sys_dconf:
          provision: true
        sys_dconf_db_local: "{{ test_sys_dconf_db_local }}"
      ansible.builtin.include_role:
        name: "sys_dconf"
...
