---
sys_user_platforms:
  - "CentOS8"
  - "OracleLinux8"
  - "Ubuntu20"
  - "Ubuntu21"
  - "Fedora33"
  - "Fedora35"
  - "Debian10"
  - "Debian11"

sys_user_base:
  paths:
    home: '/home'
    xdg_config: ".config"
  access:
    mode:
      dir: "0700"
      file: "0600"

#sys_user___setup_group: ~
#sys_user___setup_user1: ~
#sys_user___setup_user2: ~
#sys_user___setup_user3: ~
#sys_user___setup_path: ~
sys_user___setup_home: ~
...
