---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision APT repository"
      vars:
        sys_repository:
          provision: true
        sys_repository_catalog_apt:
          azure-cli: true
        sys_repository_custom_apt:
          - name: "azure-cli"
            suite: "focal"
            component: "main"
            url: "https://packages.microsoft.com/repos/azure-cli"
            pgpkey: "https://packages.microsoft.com/keys/microsoft.asc"
      ansible.builtin.include_role:
        name: "sys_repository"
...
