---
- name: "Verify"
  hosts: centos
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Discover packages"
      ansible.builtin.package_facts:
        manager: "auto"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_repository"

    - name: "Verify repository package is installed"
      ansible.builtin.assert:
        that:
          - item in ansible_facts['packages']
      loop:
        - "centos-release-ansible-29"
...
