---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Setup custom service"
      vars:
        sys_subsystem:
          setup: true
        sys_subsystem_custom:
          - name: "prometheusd"
            description: "Prometheus Server"
            type:
              simple: true
            working_directory: "/var/opt/prometheus/run"
            user: "promsrv"
            exec_start: "{{
              '/opt/prometheus/bin/prometheus' +
                ' --config.file ' +
                  '/opt/prometheus/etc/prometheus.yml'
                ' --storage.tsdb.path ' +
                  '/var/opt/prometheus/db'
            }}"
            restart:
              on_failure: true
            std_output:
              journal: true
            std_error:
              journal: true
            wanted_by:
              multi_user: true
      ansible.builtin.include_role:
        name: "sys_subsystem"
...
