---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_subsystem"

    - name: "Discover path: service"
      ansible.builtin.stat:
        get_checksum: false
        follow: false
        get_mime: false
        get_attributes: false
        path: "{{
          sys_subsystem_base['paths']['units'] + '/' +
          'prometheusd.service'
        }}"
      register: test_path_stats

    - name: "Verify the service was created"
      ansible.builtin.assert:
        that:
          - test_path_stats['stat']['exists']
...
