---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Deploy required packages"
      vars:
        sys_shell:
          resolve_prereq: true
          setup: true
        sys_shell_catalog:
          bash: true
        sys_shell_users: "{{ test_sys_shell_users_bash }}"
      ansible.builtin.include_role:
        name: "sys_shell"
...
