---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_shell"

    - name: "Verify that core variables are set"
      ansible.builtin.assert:
        that:
          - sys_shell_base is defined
          - sys_shell_application is defined

    - name: "Verify that defaults are set"
      ansible.builtin.assert:
        that:
          - sys_shell_catalog is defined
          - sys_shell is defined
...
