---
- name: "Side Efect"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Remove test file"
      ansible.builtin.file:
        state: "absent"
        path: "{{ test_target }}"
...
