---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision YUM repository"
      vars:
        sys_repository:
          prepare: true
          deploy: true
          provision: true
        sys_repository_catalog_yum:
          azure-cli: true
        sys_repository_custom_yum:
          - name: "azure-cli"
            description: "Azure CLI official RPM Repository"
            url: "https://packages.microsoft.com/yumrepos/azure-cli"
            gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
      ansible.builtin.include_role:
        name: "sys_repository"
...
