---
- name: "System / Repository / Deploy / Snap / Enable EPEL for SnapD package"
  vars:
    sys_repository_catalog_distro:
      epel: true
  ansible.builtin.include_tasks:
    file: "sys_repository_provision.yml"
  when:
    - ansible_distribution == "CentOS" or
      ansible_distribution == "OracleLinux"

- name: "System / Repository / Deploy / Snap / CLI"
  become: true
  ansible.builtin.package:
    state: "present"
    name: "{{ sys_repository_packages['snap'] }}"
  register: "sys_repository___deploy_result"

- name: "System / Repository / Deploy / Snap / Enable SnapD"
  become: true
  ansible.builtin.command:
    argv:
      - "{{ sys_repository_base['run']['systemctl'] }}"
      - "enable"
      - "--now"
      - "snapd.socket"
  when:
    - sys_repository___deploy_result['changed']
  changed_when: false
...
