---
# Try to update, ignore errors even when brew is not yet installed
- name: "System / Repository / Prepare / Brew / Update repository cache"
  ansible.builtin.command:
    chdir: "{{ sys_repository_base['paths']['homebrew_home'] }}"
    argv:
      - "{{ sys_repository_base['run']['su'] }}"
      - "-l"
      - "-c"
      - "{{ sys_repository_base['run']['brew'] + ' update' }}"
      - "{{ sys_repository_owners['homebrew']['user'] }}"
  changed_when: false
  failed_when: false
  no_log: true
...
