---
- name: "System / Shell / Setup / Profile / Options / Identify"
  ansible.builtin.set_fact:
    sys_shell___setup_profile:
      name: "{{ sys_shell___setup_user['name'] }}"
      flavour: "{{ sys_shell___setup_user['flavour'] }}"
      access:
        user:
          owner: "{{ sys_shell___setup_user['access']['user']['owner'] | default( sys_shell___setup_user['name'] ) }}"
        group:
          owner: "{{ sys_shell___setup_user['access']['group']['owner'] | default( sys_shell___setup_user['name'] ) }}"
        mode:
          file: "{{
            sys_shell___setup_user['access']['mode']['file'] |
            default( sys_shell_user_default[sys_shell___setup_user['flavour']]['access']['mode']['file'] )
            }}"
          dir: "{{
            sys_shell___setup_user['access']['mode']['dir'] |
            default( sys_shell_user_default[sys_shell___setup_user['flavour']]['access']['mode']['dir'] )
            }}"
      home: "{{
        sys_shell___setup_user['home'] |
        default( sys_shell_base['paths']['home_root'] + '/' + sys_shell___setup_user['name'] )
        }}"
      theme: "{{ sys_shell_user_default[sys_shell___setup_user['flavour']]['theme'] }}"
      modules: "{{ sys_shell_user_default[sys_shell___setup_user['flavour']]['modules'] }}"
      paths: "{{ sys_shell___setup_user['paths'] | default() }}"
      variables: "{{ sys_shell___setup_user['variables'] | default() }}"
      sources: "{{ sys_shell___setup_user['sources'] | default() }}"
      include_system: "{{ sys_shell___setup_user['include_system'] | default() }}"
...
