---
- name: "System / Shell / Deploy / ZSH"
  ansible.builtin.include_tasks:
    file: "sys_shell_deploy_zsh.yml"
  when:
    - sys_shell_catalog['zsh'] is defined

- name: "System / Shell / Deploy / CSH"
  ansible.builtin.include_tasks:
    file: "sys_shell_deploy_csh.yml"
  when:
    - sys_shell_catalog['csh'] is defined

- name: "System / Shell / Deploy / KSH"
  ansible.builtin.include_tasks:
    file: "sys_shell_deploy_ksh.yml"
  when:
    - sys_shell_catalog['ksh'] is defined

- name: "System / Shell / Deploy / Bash"
  ansible.builtin.include_tasks:
    file: "sys_shell_deploy_bash.yml"
  when:
    - sys_shell_catalog['bash'] is defined
...
