---
- name: "Side Efect"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  vars:
    test_target: "/tmp/test_sys_package_provision_binary_bzip2_target"
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Remove test target"
      ansible.builtin.file:
        state: "absent"
        path: "{{ test_target }}"
...
