---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  vars:
    test_target: "/tmp/test_sys_package_provision_binary_bzip2_target"
    test_bin: "restic_0.12.0_linux_amd64"
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_package"

    - name: "Detect target path"
      ansible.builtin.stat:
        path: "{{ test_target + '/' + test_bin }}"
      register: file_stat

    - name: "Verify app is installed"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
