---
- name: "Converge"
  hosts: centos
  gather_facts: false
  tasks:

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision distro repo"
      vars:
        sys_repository:
          provision: true
        sys_repository_catalog_distro:
          ansible-29: true
          epel: true
        sys_repository_custom_distro:
          - name: "ansible-29"
            package: "centos-release-ansible-29"
      ansible.builtin.include_role:
        name: "sys_repository"
...
