---
sys_shell_base:
  files: "{{ sys_shell_base_common['files'] }}"
  run: "{{ sys_shell_base_common['run'] }}"
  templates: "{{ sys_shell_base_common['templates'] }}"
  paths: "{{ sys_shell_base_common['paths'] }}"
  access:
    user:
      owner: "root"
    group:
      owner: "wheel"
    mode:
      dir: "0755"
      file: "0644"
      exe: "0755"

sys_shell_profiles:
  zsh: {}
  bash:
    brew:
      latest:
        supported: true
        packages:
          - name: "bash"
  ksh: {}
  csh: {}
  ohmyzsh: "{{ sys_shell_profiles_common['ohmyzsh'] }}"
  p10k: "{{ sys_shell_profiles_common['p10k'] }}"

sys_shell_application:
  zsh: {}
  bash:
    name: "bash"
    type: "brew"
    version: "latest"
    installed: "{{ sys_shell_catalog['bash'] | default(false) }}"
  ksh: {}
  csh: {}
  ohmyzsh: "{{ sys_shell_application_common['ohmyzsh'] }}"
  p10k: "{{ sys_shell_application_common['p10k'] }}"
...
