---
test_sys_shell_users_bash:
  - name: "test"
    flavour: "bash"
    home: "/home/test"
    paths:
      - "/test1"
      - "/test2"
    include_system: true
    sources:
      - "/test-source.sh"
    variables:
      - name: "TEST1"
        value: "value1"
        export: true
      - name: "TEST2"
        value: "value2"
        export: true
test_sys_shell_users_zsh:
  - name: "test"
    flavour: "zsh"
    home: "/home/test"
    paths:
      - "/test1"
      - "/test2"
    include_system: true
    sources:
      - "/test-source.sh"
    variables:
      - name: "TEST1"
        value: "value1"
        export: true
      - name: "TEST2"
        value: "value2"
        export: true

verify_path_zshrc: "{{ test_sys_shell_users_bash[0]['home'] + '/' + sys_shell_base['files']['zshrc'] }}"
verify_path_bash_rc: "{{ test_sys_shell_users_zsh[0]['home'] + '/' + sys_shell_base['files']['bash_rc'] }}"
...
