---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_package"

    - name: "Detect if resource is present"
      ansible.builtin.stat:
        path: "{{ sys_package_base['paths']['repository'] }}"
      register: test_result

    - name: "Verify that the resource was created"
      ansible.builtin.assert:
        that:
          - test_result['stat']['exists']
...
