---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Setup service"
      vars:
        sys_mc:
          setup: true
        sys_mc_users:
          - name: "{{ test_user }}"
            group: "{{ test_group }}"
            home: "{{ test_home }}"
      ansible.builtin.include_role:
        name: "sys_mc"
...
