---
- name: "System / Package / Provision / Type: brew / Uninstall / Check required parameters"
  ansible.builtin.assert:
    quiet: true
    that:
      - "'packages' in sys_package___application"
      - sys_package___application['packages'] is not none
      - sys_package___application['packages'] | length > 0

- name: "System / Package / Provision / Type: brew / Uninstall / Install"
  become: true
  become_user: "{{ sys_repository_base['access']['user']['homebrew'] }}"
  community.general.homebrew:
    name: "{{
      sys_package___application['packages'] |
      map( attribute = 'name' ) |
      list()
      }}"
    state: "absent"
    update_homebrew: false
    upgrade_all: false

- name: "System / Package / Provision / Type: brew / Uninstall / CleanUp"
  ansible.builtin.include_tasks:
    file: "sys_package_provision_cleanup.yml"
  when:
    - "'cleanup' in sys_package___application"
    - sys_package___application['cleanup'] is not none
    - sys_package___application['cleanup'] | length > 0
...
