---
- name: "Converge"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:

    - name: "Load common test vars"
      ansible.builtin.include_vars:
        file: "../test_vars.yml"

    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Provision brew repository"
      vars:
        sys_repository:
          provision: true
        sys_repository_managers:
          brew: true
        sys_repository_catalog_brew:
          hashicorp: true
        sys_repository_custom_brew:
          - name: "hashicorp"
            source: "hashicorp/tap"
      ansible.builtin.include_role:
        name: "sys_repository"
...
