---
- name: "Verify"
  hosts: "{{ lookup('env', 'DEVAP_TEST_PLATFORM') | default('all') }}"
  gather_facts: false
  tasks:
    - name: "Discover platform"
      ansible.builtin.setup:
        gather_subset: "min"
        gather_timeout: "10"

    - name: "Load role variables"
      ansible.builtin.include_role:
        public: true
        name: "sys_user"

    - name: "Detect home directory"
      ansible.builtin.stat:
        path: "/home/myhome"
      register: file_stat

    - name: "Check home was created"
      ansible.builtin.assert:
        that:
          - file_stat['stat']['exists']
...
